#!/usr/bin/env bash
# Configures localhost and facebook.com name resolution

{
  echo "127.0.0.2 localhost"
  echo "8.8.8.8 facebook.com"
  echo "::1 ip6-localhost ip6-loopback"
  echo "fe00::0 ip6-localnet"
  echo "ff00::0 ip6-mcastprefix"
  echo "ff02::1 ip6-allnodes"
  echo "ff02::2 ip6-allrouters"
} > /etc/hosts
